export const UPDATE_FIELD_AUTH = "UPDATE_FIELD_AUTH";
export const REG_USER ="REG_USER";


export const LOGIN_USER = "LOGIN_USER";
export const UPDATE_FIELD_LOGIN = "UPDATE_FIELD_LOGIN";

export const CONTACT_FORM = "CONTACT_FORM";
export const UPDATE_FIELD_CONTACT = "UPDATE_FIELD_CONTACT";

export const UPDATE_RECAPTCHA = "UPDATE_RECAPTCHA";
export const VERIFY_USER = "VERIFY_USER";