// export const REG_FIRSTNAME_FIELD_CHANGED = "REG_FIRSTNAME_FIELD_CHANGED";
// export const REG_LASTNAME_FIELD_CHANGED = "REG_LASTNAME_FIELD_CHANGED";
// export const REG_EMAIL_FIELD_CHANGED = "REG_EMAIL_FIELD_CHANGED";
// export const REG_PASSWORD_FIELD_CHANGED = "REG_PASSWORD_FIELD_CHANGED";
// export const REG_PASSWORD_CONFIRM_FIELD_CHANGED = "REG_PASSWORD_CONFIRM_FIELD_CHANGED";
export const UPDATE_FIELD_AUTH = "UPDATE_FIELD_AUTH";
export const REG_USER ="REG_USER";


export const LOGIN_USER = "LOGIN_USER";